### PR TITLE
Added 256x256 icon

### PR DESCRIPTION
**Pull request by SirYodaJedi**
For the sake of full transparency, here's an archive of all the images I used and created when upscaling the icon (partly done with [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe), the rest manually.
[edit history.zip](https://github.com/sonicretro/sadx-mod-loader/files/3990999/edit.history.zip)

### CODE REVIEW

**Comment by MainMemory** [comment]
I feel like I was given a 256x256 icon initially, but I just didn't use it.

**Comment by SirYodaJedi** [comment]
I mean, if there is a natively 256x256 icon, then please go for it instead of this. Due to the weird way Windows works, File Explorer will display big transparent borders around the icon in certain views if a 256x256 (or higher) icon can't be found, even if the actual viewport size is less than 256x256. Kinda a pet peeve of mine.

Just realized my icon isn't WinXP compatible (compressed icon). I'm going to quickly fix that, since the readme specifies XP in the minimum requirements.

**Comment by MainMemory** [comment]
[MDWAaGjQPVwy.zip](https://github.com/sonicretro/sadx-mod-loader/files/3992010/MDWAaGjQPVwy.zip)

**Comment by SirYodaJedi** [comment]
Do you mind if I remove the 192x192 layer to reduce the executable size? I can't think of a single time where it would need to be used instead of just scaling down the 256x256 version.

**Comment by MainMemory** [comment]
Sure.

**Comment by SirYodaJedi** [comment]
Okay, it should be ready.

**Pull request merged**
