### PR TITLE
Change a type and field name in ObjectMaster

### PR DESCRIPTION
**Pull request by Raytwo**
Found this out while investigating some GUI stuff.

### CODE REVIEW

**Comment by michael-fadely** [comment]
This pointer is also used by entities for miscellaneous data.

**Comment by MainMemory** [comment]
Is that field valid for all objects?

**Comment by Raytwo** [comment]
I'm almost certain it is but I'm a novice at reverse engineering so you might want to double check just to make sure.

**Comment by PiKeyAr** [comment]
Since we have the full struct from the symbols now, I think we no longer need this.
The field in question is a pointer to an `anywk` structure, which does indeed get allocated separately when objects need it.

**Pull request closed without merging**
